### ISSUE TITLE
PSK with $ does not work

### ISSUE THREAD

**Issue by scurth** [seemoo-lab/openwifipass#3]
When using a $ from cmdline, the $ will be handled as a variable, as expected. Unfortunately, quotes around the psk string does not work.

sudo -E python3 -m openwifipass --ssid WIFI --psk abc$def

The only way for me to get it working was to escape the dollar sign:

sudo -E python3 -m openwifipass --ssid WIFI --psk abc\$def

As this is not a python issue, but rather a cmdline topic, I think it may be good to always expect the psk with single quotes as it is quite likely to contain a $.

And many, many thanks for this awesome tool.

**Comment by schmittner** [comment]
Thanks @scurth, that's correct. You either have to escape the individual characters or use single quotes (`'`). Will add a note in the Readme.

**Comment by mdapplem229** [comment]
Hi

**Comment by mdapplem229** [comment]
Good
